version: "3.9"
services:
  web:
  #django_todo_app:
    container_name: "django_todo_app"
    build: .
    ports:
      - 8000:8000
    #volumes:                            # Note: If using persistent volume, any changes made in index.html will not relect even if using compose up or down. So first comment volume, then do the modification.
     # - django-todo-app-vol:/app

 # mysql_db:
  #  container_name: "django_todo_db"
   # image: mysql:5.7
    #ports:
     # - 3306:3306
    #environment:
     # MYSQL_ROOT_PASSWORD: "test@123"

  #nginx_server:
   # container_name: "nginix_server"
    #image: nginx:latest
    #ports:
     # - 80:80

#volumes:
 # django-todo-app-vol:
